### ISSUE TITLE
If PhantomJS hangs, the whole build hangs on Bamboo (Windows)

### ISSUE THREAD

**Issue by SimenB** [searls/jasmine-maven-plugin#183]
I don't know what info you need, so I'll just paste in the stacktraces. The build continues to run until the process is killed. We had the same problem with Phantom 1.9.0, and upgrading didn't help.

https://gist.github.com/SimenB/5874938
https://gist.github.com/SimenB/5874941

**Comment by ahettlin** [comment]
Not sure if this is related or if I should create a separate issue, but we are having a similar issue where our build hangs in Bamboo.  I have Jasmine integrated with Saga code coverage.  It works great, but my guess is that the server for Jasmine keeps running after Saga is done so Bamboo keeps our build running even though nothing is happening.  Not sure if this should be filed as a bug, or more of a feature request for a maven command to shut down Jasmine at the end of the build.

**Comment by klieber** [comment]
Closing this ticket since PhantomJS support is being dropped since the project is [no longer in development](ariya/phantomjs#15344).

There is an alpha version of the plugin available that uses headless Chrome available:
https://github.com/searls/jasmine-maven-plugin/releases/tag/jasmine-maven-plugin-3.0-alpha-01
