### ISSUE TITLE
A fixed jasmine:test port

### ISSUE THREAD

**Issue by cryptocamtech** [searls/jasmine-maven-plugin#296]
Under here: https://searls.github.io/jasmine-maven-plugin/test-mojo.html#serverPort it clearly states that the jasmine:test goal always uses a random available port .

However I have a fixed CORS setting that relies on a particular localhost port (wildcards aren't supported).

Is there a way this could be fixed for this situation? jasmine:bdd is fine, but jasmine:test is broken for me.

**Comment by klieber** [comment]
@camster444, sorry for the late reply.  I think I would need to understand your use case some more.  It sounds to me like you are calling out to a service from your specs and so you need the host and port to match the allowed origin on your server.  If I am correct then this is really not a supported use case.  It's usually considered bad practice to have a unit test that depends on another system being available like a database or a web service.  I'd recommend you mock out that service so that your tests can stay focused on testing your JavaScript code.

Of course, if that is not your use case then please provide me some more details so I can better understand.

**Comment by camster444** [comment]
Hi Kyle,
    My tests need to go to a known port # as it needs to be set for
      cross domain permissions. I'm not going to mock this up as it's a
      major server.
    
    i.e. the server will reject requests from clients that are
      unknown and a wildcard port isn't supported.
    I'm using the browser based Jasmine testing, but I've had to
      bypass the automated testing as it just doesn't work.
    Cam
    
    
    
    
    
    
    On 11/10/2016 4:41 AM, Kyle Lieber
      wrote:
    
    
      @camster444, sorry for the late
        reply. I think I would need to understand your use case some
        more. It sounds to me like you are calling out to a service from
        your specs and so you need the host and port to match the
        allowed origin on your server. If I am correct then this is
        really not a supported use case. It's usually considered bad
        practice to have a unit test that depends on another system
        being available like a database or a web service. I'd recommend
        you mock out that service so that your tests can stay focused on
        testing your JavaScript code.
      Of course, if that is not your use case then please provide me
        some more details so I can better understand.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/searls/jasmine-maven-plugin","title":"searls/jasmine-maven-plugin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/searls/jasmine-maven-plugin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@klieber in #296: @camster444, sorry for the late reply.  I think I would need to understand your use case some more.  It sounds to me like you are calling out to a service from your specs and so you need the host and port to match the allowed origin on your server.  If I am correct then this is really not a supported use case.  It's usually considered bad practice to have a unit test that depends on another system being available like a database or a web service.  I'd recommend you mock out that service so that your tests can stay focused on testing your JavaScript code.\r\n\r\nOf course, if that is not your use case then please provide me some more details so I can better understand."}],"action":{"name":"View Issue","url":"https://github.com/searls/jasmine-maven-plugin/issues/296#issuecomment-252705139"}}}
    
    
    -- 
Cameron Hamilton-Rich
41 Tenth Ave,
Coorparoo, 4151
Ph: 0421 838287
Email: camhrich@gmail.com

**Comment by SteffenL** [comment]
I have quite a bit of a problem as well, and I am not sure how to solve this in a sensible manner.

I need to run unit tests on multiple real browsers on different platforms (both desktop and mobile). Tests run on Selenium grid nodes with the remote WebDriver. These nodes connect to the web server remotely.

The reason why this does not work well for me is that a lot of unit tests use crypto features that require a secure origin for non-local requests (at least with the Chrome browser).

My idea was to generate a self-signed certificate and to specify the `acceptSslCerts` WebDriver capability. When I specify `org.eclipse.jetty.server.ssl.SslSelectChannelConnector` for the property `jasmine.connectorClass`, I seem to have multiple issues:
- I cannot see any way to way to specify my own path to a keystore that I can generate every time I run tests, or even use a clean keystore made by hand.
- When the keystore does not already exist, I get the error `java.io.FileNotFoundException: /Users/user/.keystore (No such file or directory)` when running tests.
- When the keystore _does_ exist, I get the error `java.security.UnrecoverableKeyException: Password must not be null`.

My other idea was to run a reverse proxy so that I would not need to change the connector class, but instead just specify `https` for the `jasmine.uriScheme` property. In order for this to work, the remote client must know the port the proxy listens on, and the proxy must know the port to forward requests to. If I should somehow use the value of the `jasmine.serverPort` property to configure the proxy, then the proxy must somehow start and stop in a reliable manner as part of the test phase.

The web server (hosting the tests) and all of the Selenium grid nodes are currently on the same local network.

I hope that this explains my use case well enough, because I have to admit that I am somewhat stuck.

Thank you for any assistance you can provide!
