### ISSUE TITLE
The documentation page is down

### ISSUE THREAD

**Issue by cherealnice** [searls/jasmine-maven-plugin#347]
Hi,

I've just tried to access the documentation page at https://justin.searls.co/jasmine-maven-plugin/ and it seems to be down. Thanks!

**Comment by klieber** [comment]
@searls I'm assuming this is because maybe something changed on your github account.  The documentation used to be hosted at https://searls.github.io/jasmine-maven-plugin but that is automatically forwarding to https://justin.searls.co/jasmine-maven-plugin now and doesn't exist.  I don't think I have access to mess with the github pages setup to see what is happening.

**Comment by searls** [comment]
@klieber yeah, apologies. I don't have much idea either. I'll see if I can reverse the setting

**Comment by searls** [comment]
Ok I think https://searls.github.io/jasmine-maven-plugin/ should work again. Sorry!
