### ISSUE TITLE
The link to documentation at github is broken.

### ISSUE THREAD

**Issue by mihxil** [searls/jasmine-maven-plugin#508]
It links to https://searls.github.com/jasmine-maven-plugin

But that should be https://searls.github.io/jasmine-maven-plugin

**Comment by mihxil** [comment]
This is the smallest issue ever. Just fix it I'd say. It isn't in code or i would issue a PR...

**Comment by klieber** [comment]
@mihxil Sorry, I don't seem to have access to fix it.  I guess since I don't own the repository.  Weird because I'm pretty sure I set that URL way back when but I'm guess permissions on Github have changed since 2013.  

Honestly, I really haven't used this plugin in about 6 years so it doesn't really get much of my attention.  I also really don't feel it's the best solution anymore.  I'd recommend using Node / NPM to run your javascript tests and if you want it tied into your maven build the [frontend-maven-plugin](https://github.com/eirslett/frontend-maven-plugin) is great.

**Comment by klieber** [comment]
@searls if you have a minute to spare this is just referring to updating the website url in the repository details.  It's still using `github.com` instead of `github.io`.

**Comment by searls** [comment]
Done! Thanks Kyle for reaching out, I hope you're doing well 💙💚💖💛💜
